name: Submit Dependencies
on:
  push:
    branches: [main]


jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for dependency submission
    steps:
      - uses: actions/checkout@v6
      - uses: jessehouwing/actions-dependency-submission@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
